codecov:
  require_ci_to_pass: yes
  branch: main

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  ignore:
    - "cmd/"
    - "example/"
    - "**/*_test.go"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        paths:
          - "pkg"
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
        paths:
          - "pkg"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no