blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://freedatavalidator.xyz
    about: Check out our documentation for common questions
  - name: Go Package Documentation
    url: https://pkg.go.dev/github.com/akhilesharora/serdeval
    about: View the Go package documentation