name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # First, run all checks in parallel
  required-checks:
    name: Required Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.x
    
    - name: Check formatting
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Go code is not formatted. Please run 'gofmt -w .'"
          gofmt -d .
          exit 1
        fi
    
    - name: Check go mod tidy
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "go.mod or go.sum is not tidy. Please run 'go mod tidy'"
          git diff
          exit 1
        fi
    
    - name: Check for TODO comments
      run: |
        if grep -r "TODO" --include="*.go" .; then
          echo "Found TODO comments. Please resolve them before merging."
          exit 1
        fi || true
    
    - name: License check
      run: |
        if ! [ -f "LICENSE" ]; then
          echo "LICENSE file is missing"
          exit 1
        fi

  # Summary job that other jobs depend on
  pr-status:
    name: PR Status Check
    runs-on: ubuntu-latest
    needs: [required-checks]
    if: always()
    steps:
    - name: Check all jobs
      run: |
        if [ "${{ contains(needs.*.result, 'failure') }}" = "true" ]; then
          echo "❌ Some checks failed. Please fix the issues and push again."
          exit 1
        else
          echo "✅ All checks passed!"
        fi